LocalTheatreCompany/Areas/Administration/Controllers/UserAdministrationController.cs
using LocalTheatreCompany.Models;
using LocalTheatreCompany.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LocalTheatreCompany.Areas.Administration.Controllers
{
    public class UserAdministrationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Administration/UserAdministration
        public ActionResult Index()
        {
            List<UserViewModel> theUsers = new List<UserViewModel>();
            foreach(ApplicationUser aUser in db.Users)
            {
                UserViewModel uViewModel = new UserViewModel();
                uViewModel.Id = aUser.Id;
                uViewModel.UserName = aUser.UserName;
                uViewModel.Email = aUser.Email;
                uViewModel.IsAdmin = aUser.IsAdmin;
                uViewModel.IsSuspended = aUser.IsSuspended;
                theUsers.Add(uViewModel);

            }
            return View(theUsers);
        }

        // GET: Administration/UserAdministration/Details/5
        public ActionResult Details(string id)
        {
            ApplicationUser aUser = db.Users.Single(m => m.Id == id);
            UserViewModel uvm = new ViewModel.UserViewModel();
            uvm.UserName = aUser.UserName;
            uvm.Email = aUser.Email;
            uvm.IsAdmin = aUser.IsAdmin;
            uvm.IsSuspended = aUser.IsSuspended;

            return View(uvm);
        }

        // GET: Administration/UserAdministration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administration/UserAdministration/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Administration/UserAdministration/Edit/5
        public ActionResult Edit(string id)
        {
            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel uvm = new UserViewModel();
            ApplicationUser applicationUser = db.Users.Find(id);
            if(applicationUser == null)
            {
                return HttpNotFound();

            }else
            {
                uvm.UserName = applicationUser.UserName;
                uvm.Email = applicationUser.Email;
                uvm.IsAdmin = applicationUser.IsAdmin;
                uvm.IsSuspended = applicationUser.IsSuspended;
            }
            return View(uvm);
        }

        // POST: Administration/UserAdministration/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserViewModel userViewModel)
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            ApplicationUser au = db.Users.Find(userViewModel.Id);
            au.Id = userViewModel.Id;
            au.UserName = userViewModel.UserName;
            au.Email = userViewModel.Email;
            au.IsAdmin = userViewModel.IsAdmin;
            au.IsSuspended = userViewModel.IsSuspended;

           


            if (ModelState.IsValid)
            {
                if ((au.IsAdmin) && (!UserManager.IsInRole(au.Id, "Admin")))
                    UserManager.AddToRole(au.Id, "Admin");
                else if ((!au.IsAdmin) && (UserManager.IsInRole(au.Id, "Admin")))
                    UserManager.RemoveFromRoles(au.Id, "Admin");
                if ((au.IsSuspended) && (!UserManager.IsInRole(au.Id, "Limited")))
                    UserManager.AddToRole(au.Id, "Limited");
                else if ((!au.IsSuspended) && (UserManager.IsInRole(au.Id, "Limted")))
                    UserManager.RemoveFromRoles(au.Id, "Limited");


                db.Entry(au).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userViewModel);

        }

        // GET: Administration/UserAdministration/Delete/5
        public ActionResult Delete(string id)
        {
            UserViewModel uvm = new UserViewModel();
            ApplicationUser applicationUser = db.Users.Find(id);
            if(applicationUser == null)
            {
                return HttpNotFound();
            }else
            {
                uvm.Id = applicationUser.Id;
                uvm.UserName = applicationUser.UserName;
                uvm.Email = applicationUser.Email;
                uvm.IsAdmin = applicationUser.IsAdmin;
                uvm.IsSuspended = applicationUser.IsSuspended;

            }
            return View(uvm);
        }

        // POST: Administration/UserAdministration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteComfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

LocalTheatreCompany/Views/Shared/_AddComment.cshtml
@model LocalTheatreCompany.Models.Comment

<em><strong> Add a new comment</strong></em>
@if (!User.IsInRole("Limited")) {
using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.articleId)
        @Html.HiddenFor(model => model.commentId)

        <div class="form-group">
            <div class="col-md-2">
                @Html.EditorFor(model => model.commentText)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")}

LocalTheatreCompany/Views/Shared/_DeleteComment.cshtml
@model LocalTheatreCompany.Models.Comment



    @using (Html.BeginForm("DeleteComment", "Articles"))
    {
        @Html.AntiForgeryToken()
        <div>
            <h4>Comments</h4>
            @Html.HiddenFor(model => model.articleId)
            <dl class="dl-horizontal">
                @Html.HiddenFor(model => model.commentId)
                <dt>@Html.DisplayNameFor(model => model.commentText)</dt>
                <dd>@Html.DisplayFor(model => model.commentText)</dd>

                <dt> @Html.DisplayNameFor(model => model.CommentDate)</dt>
                <dd>@Html.DisplayFor(model => model.CommentDate)</dd>

                <dt> @Html.DisplayNameFor(model => model.commentAuthor)</dt>
                <dd>@Html.DisplayFor(model => model.commentAuthor)</dd>
            </dl>

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn default" />
            </div>
               


        </div>
    }

LocalTheatreCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Local Theatre' Company", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                   
                    @if (User.Identity.IsAuthenticated)
                    {
                        
                        <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin Area", "Index","UserAdministration", new { Area ="Administration"},null)</li>
                    }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>